# Dataset: AE
# Description: Adverse events dataset used to create pharmaversesdtm::ae

# Load pharmaversesdtm::ae and convert into raw dataset ----
sdtm_ae <- pharmaversesdtm::ae
ae_raw <- sdtm_ae |>
  dplyr::mutate(
    STUDY = "CDISCPILOT01",
    PATNUM = substr(USUBJID, 4, 11),
    FOLDER = "AE",
    FOLDERL = "Adverse Events",
    IT.AETERM = tools::toTitleCase(tolower(AETERM)),
    IT.AESEV = ifelse(AESEV == "MILD", "Mild Adverse Event",
                      ifelse(AESEV == "MODERATE", "Moderate Adverse Event",
                             ifelse(AESEV == "SEVERE", "Severe Adverse Event", AESEV))),
    IT.AESER = ifelse(AESER == "Y", "Yes", "No"),
    IT.AEACN = AEACN,
    IT.AEREL = tools::toTitleCase(tolower(AEREL)),
    IT.AEREL = ifelse(IT.AEREL == "Possible", "Possibly Related",
                      ifelse(IT.AEREL == "Probable", "Probably Related",
                             ifelse(IT.AEREL == "None", "Not Related", IT.AEREL))),
    AEOUTCOME = tools::toTitleCase(tolower(AEOUT)),
    AESCAN = ifelse(AESCAN == "Y", "Yes", "No"),
    AESCNO = ifelse(AESCONG == "Y", "Yes", "No"),
    AEDIS = ifelse(AESDISAB == "Y", "Yes", "No"),
    IT.AESDTH = ifelse(AESDTH == "Y", "Yes", "No"),
    IT.AESHOSP = ifelse(AESHOSP == "Y", "Yes", "No"),
    IT.AESLIFE = ifelse(AESLIFE == "Y", "Yes", "No"),
    AESOD = ifelse(AESOD == "Y", "Yes", "No"),
    AEDTCOL = format(as.Date(AEDTC, format = "%Y-%m-%d"), "%m/%d/%Y"),
    IT.AESTDAT = ifelse(nchar(AESTDTC) == 10, format(as.Date(AESTDTC, format = "%Y-%m-%d"), "%m/%d/%Y"),
                        ifelse(nchar(AESTDTC) == 7, format(as.Date(AESTDTC, format = "%Y-%m"), "%m/%Y"),
                               ifelse(nchar(AESTDTC) == 4, format(as.Date(AESTDTC, format = "%Y"), "%Y"),
                                      AESTDTC))),
    IT.AEENDAT = ifelse(nchar(AEENDTC) == 10, format(as.Date(AEENDTC, format = "%Y-%m-%d"), "%m/%d/%Y"),
                        ifelse(nchar(AEENDTC) == 7, format(as.Date(AEENDTC, format = "%Y-%m"), "%m/%Y"),
                               ifelse(nchar(AEENDTC) == 4, format(as.Date(AEENDTC, format = "%Y"), "%Y"),
                                      AEENDTC)))
  ) |>
  dplyr::select(
    STUDY, PATNUM, FOLDER, FOLDERL, IT.AETERM, AEOUTCOME,
    AELLT, AELLTCD, AEDECOD, AEPTCD, AEHLT, AEHLTCD, AEHLGT, AEHLGTCD, AEBODSYS, AEBDSYCD, AESOC, AESOCCD,
    IT.AESEV, IT.AESER, IT.AEREL, IT.AEACN, IT.AEREL,
    AEOUTCOME, AESCAN, AESCNO, AEDIS,
    IT.AESDTH, IT.AESHOSP, IT.AESLIFE,
    AESOD, AEDTCOL, IT.AESTDAT, IT.AEENDAT
  )

# Map code from Meddra dictionary ----
# In this dataset, only the AELLTCD and AESOCCD can find a match

# Create Meddra Dictionary
meddra1 <- tibble::tribble(
  ~IT.AETERM,                          ~AELLT,                                                 ~AESOC, ~LLT_CODE, ~SOC_CODE,
  "Application Site Erythema",      "APPLICATION SITE REDNESS", "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10003058,  10018065,
  "Application Site Pruritus",      "APPLICATION SITE ITCHING", "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10003047,  10018065,
  "Diarrhoea",                      "DIARRHEA",                           "GASTROINTESTINAL DISORDERS",  10012727,  10017947,
  "Atrioventricular Block Second Degree",        "AV BLOCK SECOND DEGREE",                                    "CARDIAC DISORDERS",  10003851,  10007541,
  "Erythema",                      "ERYTHEMA",               "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10015150,  10040785,
  "Erythema",            "LOCALIZED ERYTHEMA",               "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10024781,  10040785,
  "Application Site Erythema",     "APPLICATION SITE ERYTHEMA", "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10003041,  10018065,
  "Fatigue",                       "FATIGUE", "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10016256,  10018065,
  "Bundle Branch Block Left",      "LEFT BUNDLE BRANCH BLOCK",                                    "CARDIAC DISORDERS",  10024100,  10007541,
  "Hiatus Hernia",                 "HERNIA HIATAL",                           "GASTROINTESTINAL DISORDERS",  10019914,  10017947,
  "Upper Respiratory Tract Infection",   "UPPER RESPIRATORY INFECTION",                          "INFECTIONS AND INFESTATIONS",  10046300,  10021881,
  "Application Site Vesicles",      "APPLICATION SITE BLISTER", "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10053414,  10018065,
  "Nasal Congestion",              "NASAL CONGESTION",      "RESPIRATORY, THORACIC AND MEDIASTINAL DISORDERS",  10028735,  10038738,
  "Pharyngolaryngeal Pain",                   "SORE THROAT",      "RESPIRATORY, THORACIC AND MEDIASTINAL DISORDERS",  10041367,  10038738,
  "Pruritus Generalised",          "GENERALIZED PRURITUS",               "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10018123,  10040785,
  "Arthralgia",        "GENERALIZED JOINT PAIN",      "MUSCULOSKELETAL AND CONNECTIVE TISSUE DISORDERS",  10062438,  10028395,
  "Cellulitis",             "CELLULITIS OF LEG",                          "INFECTIONS AND INFESTATIONS",  10007912,  10021881,
  "Localised Infection",           "LOCALIZED INFECTION",                          "INFECTIONS AND INFESTATIONS",  10062469,  10021881,
  "Micturition Urgency",               "URINARY URGENCY",                          "RENAL AND URINARY DISORDERS",  10046593,  10038359,
  "Pruritus",                       "ITCHING",               "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10023084,  10040785,
  "Application Site Dermatitis",         "APPLICATION SITE RASH", "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10003054,  10018065,
  "Application Site Irritation",      "APPLICATION SITE BURNING", "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10048942,  10018065,
  "Cough",                         "COUGH",      "RESPIRATORY, THORACIC AND MEDIASTINAL DISORDERS",  10011224,  10038738,
  "Eye Allergy",                   "EYE ALLERGY",                                        "EYE DISORDERS",  10015907,  10015919,
  "Eye Pruritus",                   "EYE ITCHING",                                        "EYE DISORDERS",  10015947,  10015919,
  "Eye Swelling",                  "EYES SWOLLEN",                                        "EYE DISORDERS",  10016014,  10015919,
  "Pruritus",            "ITCHING BOTH HANDS",               "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10023087,  10040785,
  "Pyrexia",                         "FEVER", "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10016558,  10018065,
  "Urinary Tract Infection",       "URINARY TRACT INFECTION",                          "INFECTIONS AND INFESTATIONS",  10046571,  10021881,
  "Application Site Irritation",   "APPLICATION SITE IRRITATION", "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10003046,  10018065,
  "Application Site Pain",         "APPLICATION SITE PAIN", "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10003051,  10018065,
  "Application Site Vesicles",     "APPLICATION SITE VESICLES", "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10048941,  10018065,
  "Rash",                          "RASH",               "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10037844,  10040785,
  "Actinic Keratosis",             "ACTINIC KERATOSIS",               "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10000614,  10040785,
  "Calculus Urethral",             "URETHRAL CALCULUS",                          "RENAL AND URINARY DISORDERS",  10046430,  10038359,
  "Depressed Mood",                "DEPRESSED MOOD",                                "PSYCHIATRIC DISORDERS",  10012374,  10037175,
  "Dyspepsia",                   "INDIGESTION",                           "GASTROINTESTINAL DISORDERS",  10021706,  10017947,
  "Epistaxis",                    "NOSE BLEED",      "RESPIRATORY, THORACIC AND MEDIASTINAL DISORDERS",  10029792,  10038738,
  "Flank Pain",                    "FLANK PAIN",      "MUSCULOSKELETAL AND CONNECTIVE TISSUE DISORDERS",  10016750,  10028395,
  "Lower Respiratory Tract Infection",                    "CHEST COLD",                          "INFECTIONS AND INFESTATIONS",  10059607,  10021881,
  "Increased Appetite",            "INCREASED APPETITE",                   "METABOLISM AND NUTRITION DISORDERS",  10021654,  10027433,
  "Headache",                      "HEADACHE",                             "NERVOUS SYSTEM DISORDERS",  10019211,  10029205,
  "Nasopharyngitis",                          "COLD",                          "INFECTIONS AND INFESTATIONS",  10009851,  10021881,
  "Vomiting",                      "VOMITING",                           "GASTROINTESTINAL DISORDERS",  10047700,  10017947,
  "Agitation",                     "AGITATION",                                "PSYCHIATRIC DISORDERS",  10001497,  10037175,
  "Application Site Urticaria",    "APPLICATION SITE URTICARIA", "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10050104,  10018065,
  "Urticaria",                         "WELTS",               "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10047906,  10040785,
  "Erythema",               "ERYTHEMA FACIAL",               "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10015212,  10040785,
  "Muscular Weakness",             "MUSCULAR WEAKNESS",      "MUSCULOSKELETAL AND CONNECTIVE TISSUE DISORDERS",  10028372,  10028395,
  "Nasal Mucosa Biopsy",           "NASAL MUCOSA BIOPSY",                                       "INVESTIGATIONS",  10057443,  10022891,
  "Pneumonia",                     "PNEUMONIA",                          "INFECTIONS AND INFESTATIONS",  10035664,  10021881,
  "Secretion Discharge",           "SECRETION DISCHARGE", "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10053459,  10018065,
  "Eye Laser Surgery",             "EYE LASER SURGERY",                      "SURGICAL AND MEDICAL PROCEDURES",  10057105,  10042613,
  "Confusional State",                     "CONFUSION",                                "PSYCHIATRIC DISORDERS",  10010300,  10037175,
  "Dyspnoea",           "SHORTNESS OF BREATH",      "RESPIRATORY, THORACIC AND MEDIASTINAL DISORDERS",  10040604,  10038738,
  "Incontinence",                  "INCONTINENCE",                          "RENAL AND URINARY DISORDERS",  10021639,  10038359,
  "Joint Dislocation",          "SHOULDER DISLOCATION",       "INJURY, POISONING AND PROCEDURAL COMPLICATIONS",  10040612,  10022117,
  "Shoulder Pain",                 "SHOULDER PAIN",      "MUSCULOSKELETAL AND CONNECTIVE TISSUE DISORDERS",  10040617,  10028395,
  "Skin Laceration",            "LACERATION OF FACE",       "INJURY, POISONING AND PROCEDURAL COMPLICATIONS",  10023584,  10022117,
  "Sudden Death",                  "SUDDEN DEATH", "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10042434,  10018065,
  "Hordeolum",                          "STYE",                          "INFECTIONS AND INFESTATIONS",  10042269,  10021881,
  "Skin Odour Abnormal",            "SKIN ODOR ABNORMAL",               "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10040903,  10040785,
  "Nausea",                        "NAUSEA",                           "GASTROINTESTINAL DISORDERS",  10028813,  10017947,
  "Parosmia",       "STRANGE SMELL SENSATION",                             "NERVOUS SYSTEM DISORDERS",  10042165,  10029205,
  "Salivary Hypersecretion",               "HYPERSALIVATION",                           "GASTROINTESTINAL DISORDERS",  10020746,  10017947,
  "Rhinorrhoea",                    "RUNNY NOSE",      "RESPIRATORY, THORACIC AND MEDIASTINAL DISORDERS",  10039296,  10038738,
  "Salivary Hypersecretion",          "INCREASED SALIVATION",                           "GASTROINTESTINAL DISORDERS",  10021677,  10017947,
  "Rash Erythematous",             "ERYTHEMATOUS RASH",               "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10015243,  10040785,
  "Application Site Perspiration", "APPLICATION SITE PERSPIRATION", "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10054838,  10018065,
  "Contusion",                        "BRUISE",       "INJURY, POISONING AND PROCEDURAL COMPLICATIONS",  10006502,  10022117,
  "Dizziness",                         "DIZZY",                             "NERVOUS SYSTEM DISORDERS",  10013580,  10029205,
  "Dizziness",               "LIGHTHEADEDNESS",                             "NERVOUS SYSTEM DISORDERS",  10024492,  10029205,
  "Feeling Abnormal",         "FOGGY FEELING IN HEAD", "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10016876,  10018065,
  "Hyperhidrosis",        "PERSPIRATION EXCESSIVE",               "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10034734,  10040785,
  "Libido Decreased",              "LIBIDO DECREASED",                                "PSYCHIATRIC DISORDERS",  10024419,  10037175,
  "Listless",                  "LISTLESSNESS",                                "PSYCHIATRIC DISORDERS",  10024643,  10037175,
  "Malaise",                       "MALAISE", "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10025482,  10018065,
  "Myalgia",                       "MYALGIA",      "MUSCULOSKELETAL AND CONNECTIVE TISSUE DISORDERS",  10028411,  10028395,
  "Pain",                      "STINGING", "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10042066,  10018065,
  "Productive Cough",              "PRODUCTIVE COUGH",      "RESPIRATORY, THORACIC AND MEDIASTINAL DISORDERS",  10036790,  10038738,
  "Respiratory Tract Congestion",  "RESPIRATORY TRACT CONGESTION",      "RESPIRATORY, THORACIC AND MEDIASTINAL DISORDERS",  10052251,  10038738,
  "Rhinitis",                        "CORYZA",                          "INFECTIONS AND INFESTATIONS",  10011214,  10021881,
  "Stomach Discomfort",                 "STOMACH UPSET",                           "GASTROINTESTINAL DISORDERS",  10042124,  10017947,
  "Cyst",                          "CYST", "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10011732,  10018065,
  "Dysphonia",                    "HOARSENESS",      "RESPIRATORY, THORACIC AND MEDIASTINAL DISORDERS",  10020201,  10038738,
  "Fatigue",                     "TIREDNESS", "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10043890,  10018065,
  "Onychomycosis",                 "ONYCHOMYCOSIS",                          "INFECTIONS AND INFESTATIONS",  10030338,  10021881,
  "Back Pain",                      "BACKACHE",      "MUSCULOSKELETAL AND CONNECTIVE TISSUE DISORDERS",  10003993,  10028395,
  "Chest Discomfort",                "CHEST PRESSURE", "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10008486,  10018065,
  "Headache",                 "FULLNESS HEAD",                             "NERVOUS SYSTEM DISORDERS",  10017468,  10029205,
  "Hyperhidrosis",                      "SWEATING",               "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10042661,  10040785,
  "Paraesthesia",                      "TINGLING",                             "NERVOUS SYSTEM DISORDERS",  10043876,  10029205,
  "Neutrophil Count Increased",    "NEUTROPHIL COUNT INCREASED",                                       "INVESTIGATIONS",  10029368,  10022891,
  "Rectal Haemorrhage",               "RECTAL BLEEDING",                           "GASTROINTESTINAL DISORDERS",  10038035,  10017947,
  "Skin Irritation",               "SKIN IRRITATION",               "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10040880,  10040785,
  "Urine Analysis Abnormal",       "URINE ANALYSIS ABNORMAL",                                       "INVESTIGATIONS",  10062226,  10022891,
  "White Blood Cell Count Increased",                 "WBC INCREASED",                                       "INVESTIGATIONS",  10056739,  10022891,
  "Insomnia",                      "INSOMNIA",                                "PSYCHIATRIC DISORDERS",  10022437,  10037175,
  "Benign Prostatic Hyperplasia",  "BENIGN PROSTATIC HYPERTROPHY",             "REPRODUCTIVE SYSTEM AND BREAST DISORDERS",  10004447,  10038604,
  "Biopsy Prostate",            "BIOPSY OF PROSTATE",                                       "INVESTIGATIONS",  10004825,  10022891
)

meddra2 <- tibble::tribble(
  ~IT.AETERM,                           ~AELLT,                                                                ~AESOC, ~LLT_CODE, ~SOC_CODE,
  "Hypercholesterolaemia",           "HYPERCHOLESTEROLEMIA",                                  "METABOLISM AND NUTRITION DISORDERS",  10020604,  10027433,
  "Chills",                         "CHILLS",                "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10008531,  10018065,
  "Cataract Operation",            "CATARACT EXTRACTION",                                     "SURGICAL AND MEDICAL PROCEDURES",  10007750,  10042613,
  "Oedema Peripheral",                      "LEG EDEMA",                "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10024127,  10018065,
  "Atrioventricular Block Second Degree",      "HEART BLOCK SECOND DEGREE",                                                   "CARDIAC DISORDERS",  10019268,  10007541,
  "Somnolence",                     "DROWSINESS",                                            "NERVOUS SYSTEM DISORDERS",  10013649,  10029205,
  "Decreased Appetite",             "DECREASED APPETITE",                                  "METABOLISM AND NUTRITION DISORDERS",  10061428,  10027433,
  "Disorientation",                 "DISORIENTATION",                                               "PSYCHIATRIC DISORDERS",  10013395,  10037175,
  "Dizziness",                      "DIZZINESS",                                            "NERVOUS SYSTEM DISORDERS",  10013573,  10029205,
  "Arthritis",                      "ARTHRITIS",                     "MUSCULOSKELETAL AND CONNECTIVE TISSUE DISORDERS",  10003246,  10028395,
  "Glaucoma",                       "GLAUCOMA",                                                       "EYE DISORDERS",  10018304,  10015919,
  "Hypotension",                    "HYPOTENSION",                                                  "VASCULAR DISORDERS",  10021097,  10047065,
  "Myocardial Infarction",          "MYOCARDIAL INFARCTION",                                                   "CARDIAC DISORDERS",  10028596,  10007541,
  "Tachycardia",                    "TACHYCARDIA",                                                   "CARDIAC DISORDERS",  10043071,  10007541,
  "Chest Discomfort",                "CHEST TIGHTNESS",                "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10008492,  10018065,
  "Weight Decreased",                    "WEIGHT LOSS",                                                      "INVESTIGATIONS",  10047900,  10022891,
  "Hyperhidrosis",             "SWEATING INCREASED",                              "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10042667,  10040785,
  "Sinus Bradycardia",              "SINUS BRADYCARDIA",                                                   "CARDIAC DISORDERS",  10040741,  10007541,
  "Transient Ischaemic Attack",     "TRANSIENT ISCHEMIC ATTACKS",                                            "NERVOUS SYSTEM DISORDERS",  10044391,  10029205,
  "Arthralgia",                      "KNEE PAIN",                     "MUSCULOSKELETAL AND CONNECTIVE TISSUE DISORDERS",  10023477,  10028395,
  "Contusion",                 "BRUISE OF HEAD",                      "INJURY, POISONING AND PROCEDURAL COMPLICATIONS",  10006503,  10022117,
  "Cystitis",              "BLADDER INFECTION",                                         "INFECTIONS AND INFESTATIONS",  10005047,  10021881,
  "Excoriation",                   "ABRASION NOS",                      "INJURY, POISONING AND PROCEDURAL COMPLICATIONS",  10000245,  10022117,
  "Skin Laceration",                      "SKIN TEAR",                      "INJURY, POISONING AND PROCEDURAL COMPLICATIONS",  10048704,  10022117,
  "Cardiac Disorder",               "CARDIAC DISORDER",                                                   "CARDIAC DISORDERS",  10061024,  10007541,
  "Influenza",                            "FLU",                                         "INFECTIONS AND INFESTATIONS",  10016790,  10021881,
  "Ventricular Septal Defect",      "VENTRICULAR SEPTAL DEFECT",                          "CONGENITAL, FAMILIAL AND GENETIC DISORDERS",  10047298,  10010331,
  "Electrocardiogram St Segment Depression",           "ST SEGMENT DEPRESSED",                                                      "INVESTIGATIONS",  10041891,  10022891,
  "Palpitations",                   "PALPITATIONS",                                                   "CARDIAC DISORDERS",  10033557,  10007541,
  "Vertigo",                        "VERTIGO",                                         "EAR AND LABYRINTH DISORDERS",  10047340,  10013993,
  "Wolff-Parkinson-White Syndrome", "WOLFF-PARKINSON-WHITE SYNDROME",                                                   "CARDIAC DISORDERS",  10048015,  10007541,
  "Abdominal Discomfort",           "ABDOMINAL DISCOMFORT",                                          "GASTROINTESTINAL DISORDERS",  10000059,  10017947,
  "Sinus Bradycardia",              "BRADYCARDIA SINUS",                                                   "CARDIAC DISORDERS",  10006098,  10007541,
  "Erythema",                       "SKIN RED",                              "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10040916,  10040785,
  "Blood Glucose Increased",              "GLUCOSE INCREASED",                                                      "INVESTIGATIONS",  10018421,  10022891,
  "Erythema",                        "REDNESS",                              "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10038198,  10040785,
  "Oedema",                          "EDEMA",                "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10014210,  10018065,
  "Oedema Peripheral",               "SWELLING OF FEET",                "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10042693,  10018065,
  "Dyspnoea",            "RESPIRATION LABORED",                     "RESPIRATORY, THORACIC AND MEDIASTINAL DISORDERS",  10038653,  10038738,
  "Atrial Fibrillation",            "ATRIAL FIBRILLATION",                                                   "CARDIAC DISORDERS",  10003658,  10007541,
  "Atrial Flutter",                 "ATRIAL FLUTTER",                                                   "CARDIAC DISORDERS",  10003662,  10007541,
  "Blister",                     "BLISTERING",                              "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10005214,  10040785,
  "Seasonal Allergy",                      "HAY FEVER",                                             "IMMUNE SYSTEM DISORDERS",  10019170,  10021428,
  "Viral Infection",                "VIRAL INFECTION",                                         "INFECTIONS AND INFESTATIONS",  10047461,  10021881,
  "Burning Sensation",              "BURNING SENSATION",                                            "NERVOUS SYSTEM DISORDERS",  10006784,  10029205,
  "Flatulence",                            "GAS",                                          "GASTROINTESTINAL DISORDERS",  10017735,  10017947,
  "Pollakiuria",              "URINARY FREQUENCY",                                         "RENAL AND URINARY DISORDERS",  10046539,  10038359,
  "Parkinson's Disease",            "DISEASE PARKINSON'S",                                            "NERVOUS SYSTEM DISORDERS",  10013113,  10029205,
  "Completed Suicide",                        "SUICIDE",                                               "PSYCHIATRIC DISORDERS",  10042462,  10037175,
  "Hyperbilirubinaemia",             "HYPERBILIRUBINEMIA",                                             "HEPATOBILIARY DISORDERS",  10020582,  10019805,
  "Dyspepsia",                        "PYROSIS",                                          "GASTROINTESTINAL DISORDERS",  10037676,  10017947,
  "Pruritus",                       "PRURITUS",                              "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10037087,  10040785,
  "Excoriation",                      "ABRASIONS",                      "INJURY, POISONING AND PROCEDURAL COMPLICATIONS",  10000266,  10022117,
  "Pruritus",                          "ITCHY",                              "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10023089,  10040785,
  "Rash Pruritic",                  "PRURITIC RASH",                              "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10037085,  10040785,
  "Wound Haemorrhage",                 "WOUND BLEEDING",                                                  "VASCULAR DISORDERS",  10051386,  10047065,
  "Ventricular Hypertrophy",   "LEFT VENTRICULAR HYPERTROPHY",                                                   "CARDIAC DISORDERS",  10049773,  10007541,
  "Abdominal Pain",               "ABDOMINAL CRAMPS",                                          "GASTROINTESTINAL DISORDERS",  10000057,  10017947,
  "Colon Cancer",                   "COLON CANCER", "NEOPLASMS BENIGN, MALIGNANT AND UNSPECIFIED (INCL CYSTS AND POLYPS)",  10009944,  10029104,
  "Anxiety",                "FEELING ANXIOUS",                                               "PSYCHIATRIC DISORDERS",  10016323,  10037175,
  "Anxiety",                 "ANXIETY ATTACK",                                               "PSYCHIATRIC DISORDERS",  10002856,  10037175,
  "Irritability",                   "IRRITABILITY",                                               "PSYCHIATRIC DISORDERS",  10022998,  10037175,
  "Syncope",                       "FAINTING",                                            "NERVOUS SYSTEM DISORDERS",  10016169,  10029205,
  "Syncope",                "SYNCOPAL ATTACK",                                            "NERVOUS SYSTEM DISORDERS",  10042771,  10029205,
  "Pruritus",                       "PRURITIS",                              "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10037086,  10040785,
  "Blood Creatine Phosphokinase Increased",                   "CPK INCREASE",                                                      "INVESTIGATIONS",  10011267,  10022891,
  "Conjunctivitis",                 "CONJUNCTIVITIS",                                                       "EYE DISORDERS",  10010741,  10015919,
  "Postnasal Drip",                 "POSTNASAL DRIP",                     "RESPIRATORY, THORACIC AND MEDIASTINAL DISORDERS",  10036402,  10038738,
  "Sinus Arrhythmia",               "SINUS ARRHYTHMIA",                                                   "CARDIAC DISORDERS",  10040739,  10007541,
  "Headache",               "FRONTAL HEADACHE",                                            "NERVOUS SYSTEM DISORDERS",  10048967,  10029205,
  "Stupor",                         "STUPOR",                                            "NERVOUS SYSTEM DISORDERS",  10042264,  10029205,
  "Vision Blurred",                 "BLURRED VISION",                                                       "EYE DISORDERS",  10005886,  10015919,
  "Heart Rate Irregular",           "HEARTBEATS IRREGULAR",                                                      "INVESTIGATIONS",  10019323,  10022891,
  "Alcohol Use",                    "ALCOHOL USE",                                                "SOCIAL CIRCUMSTANCES",  10048921,  10041244,
  "Dizziness",                   "LIGHT-HEADED",                                            "NERVOUS SYSTEM DISORDERS",  10024490,  10029205,
  "Application Site Swelling",      "APPLICATION SITE SWELLING",                "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10053424,  10018065,
  "Heart Rate Increased",           "HEART RATE INCREASED",                                                      "INVESTIGATIONS",  10019303,  10022891,
  "Hot Flush",                    "HOT FLASHES",                                                  "VASCULAR DISORDERS",  10020407,  10047065,
  "Muscle Spasms",                     "LEG CRAMPS",                     "MUSCULOSKELETAL AND CONNECTIVE TISSUE DISORDERS",  10024125,  10028395,
  "Ventricular Extrasystoles",           "VENTRICULAR BIGEMINY",                                                   "CARDIAC DISORDERS",  10050779,  10007541,
  "Abdominal Pain",                 "ABDOMINAL PAIN",                                          "GASTROINTESTINAL DISORDERS",  10000081,  10017947,
  "Constipation",                   "CONSTIPATION",                                          "GASTROINTESTINAL DISORDERS",  10010774,  10017947,
  "Myocardial Infarction", "INFERIOR MYOCARDIAL INFARCTION",                                                   "CARDIAC DISORDERS",  10057546,  10007541,
  "Atrial Hypertrophy",        "LEFT ATRIAL HYPERTROPHY",                                                   "CARDIAC DISORDERS",  10057500,  10007541,
  "Pain in Extremity",                  "PAIN IN THIGH",                     "MUSCULOSKELETAL AND CONNECTIVE TISSUE DISORDERS",  10048973,  10028395,
  "Dizziness",               "LIGHT HEADEDNESS",                                            "NERVOUS SYSTEM DISORDERS",  10024461,  10029205,
  "Myocardial Infarction",        "ANTEROSEPTAL INFARCTION",                                                   "CARDIAC DISORDERS",  10049846,  10007541,
  "Hypotension",             "LOW BLOOD PRESSURE",                                                  "VASCULAR DISORDERS",  10024895,  10047065,
  "Oedema Peripheral",               "SWELLING OF LEGS",                "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10042700,  10018065,
  "Application Site Warmth",        "APPLICATION SITE WARMTH",                "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10003060,  10018065,
  "Muscle Spasms",                          "CRAMP",                     "MUSCULOSKELETAL AND CONNECTIVE TISSUE DISORDERS",  10011285,  10028395,
  "Myocardial Infarction",   "SEPTAL MYOCARDIAL INFARCTION",                                                   "CARDIAC DISORDERS",  10057549,  10007541,
  "Pharyngeal Erythema",                     "RED THROAT",                     "RESPIRATORY, THORACIC AND MEDIASTINAL DISORDERS",  10038196,  10038738,
  "Oedema Peripheral",            "PERIPHERAL SWELLING",                "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10048959,  10018065,
  "Acrochordon Excision",               "SKIN TAG REMOVAL",                                     "SURGICAL AND MEDICAL PROCEDURES",  10056879,  10042613,
  "Nasopharyngitis",                  "COLD SYMPTOMS",                                         "INFECTIONS AND INFESTATIONS",  10009867,  10021881,
  "Skin Irritation",                "IRRITATION SKIN",                              "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10023017,  10040785,
  "Electrocardiogram t Wave Inversion",                "T WAVE INVERTED",                                                      "INVESTIGATIONS",  10042968,  10022891,
  "Application Site Discharge",     "APPLICATION SITE DISCHARGE",                "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10052162,  10018065,
  "Hip Fracture",                   "HIP FRACTURE",                      "INJURY, POISONING AND PROCEDURAL COMPLICATIONS",  10020100,  10022117
)

meddra3 <- tibble::tribble(
  ~IT.AETERM,                                           ~AELLT,                                                                ~AESOC, ~LLT_CODE, ~SOC_CODE,
  "Skin Lesion Excision",                           "SKIN LESION EXCISION",                                     "SURGICAL AND MEDICAL PROCEDURES",  10062250,  10042613,
  "Benign Prostatic Hyperplasia",                              "ENLARGED PROSTATE",                            "REPRODUCTIVE SYSTEM AND BREAST DISORDERS",        NA,        NA,
  "Blood Urine Present",                                 "BLOOD IN URINE",                                                      "INVESTIGATIONS",  10005604,  10022891,
  "Cystoscopy",                                     "CYSTOSCOPY",                                                      "INVESTIGATIONS",  10011814,  10022891,
  "Dehydration",                                    "DEHYDRATION",                                  "METABOLISM AND NUTRITION DISORDERS",  10012174,  10027433,
  "Localised Infection",                                "INFECTED FINGER",                                         "INFECTIONS AND INFESTATIONS",  10021774,  10021881,
  "Orthostatic Hypotension",                           "POSTURAL HYPOTENSION",                                                  "VASCULAR DISORDERS",  10036433,  10047065,
  "Hemianopia Homonymous",                         "HOMONYMOUS HEMIANOPSIA",                                            "NERVOUS SYSTEM DISORDERS",  10020368,  10029205,
  "Diabetes Mellitus",                                       "DIABETES",                                  "METABOLISM AND NUTRITION DISORDERS",  10012594,  10027433,
  "Drug Eruption",                                      "DRUG RASH",                              "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10062948,  10040785,
  "Allergic Granulomatous Angiitis",                        "ALLERGIC GRANULOMATOSIS",                     "RESPIRATORY, THORACIC AND MEDIASTINAL DISORDERS",  10001713,  10038738,
  "Biopsy",                                         "BIOPSY",                                                      "INVESTIGATIONS",  10004720,  10022891,
  "Feeling Cold",                                   "FEELING COLD",                "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10016326,  10018065,
  "Nightmare",                                      "NIGHTMARE",                                               "PSYCHIATRIC DISORDERS",  10029412,  10037175,
  "Rash Maculo-Papular",                             "MACULOPAPULAR RASH",                              "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10025424,  10040785,
  "Rash Papular",                                   "PAPULAR RASH",                              "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10033726,  10040785,
  "Application Site Bleeding",                      "APPLICATION SITE BLEEDING",                "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10048938,  10018065,
  "Syncope",                                        "SYNCOPE",                                            "NERVOUS SYSTEM DISORDERS",  10042772,  10029205,
  "Blood Alkaline Phosphatase Increased",                                "ALK PHOS RAISED",                                                      "INVESTIGATIONS",  10001669,  10022891,
  "Contusion",                               "BRUISING OF FACE",                      "INJURY, POISONING AND PROCEDURAL COMPLICATIONS",  10006507,  10022117,
  "Dizziness",                                     "FELT FAINT",                                            "NERVOUS SYSTEM DISORDERS",  10016379,  10029205,
  "Facial Bones Fracture",                                 "FRACTURED NOSE",                      "INJURY, POISONING AND PROCEDURAL COMPLICATIONS",  10017300,  10022117,
  "Fall",                                           "FALL",                      "INJURY, POISONING AND PROCEDURAL COMPLICATIONS",  10016173,  10022117,
  "Nephrolithiasis",                                   "KIDNEY STONE",                                         "RENAL AND URINARY DISORDERS",  10023436,  10038359,
  "Salivary Hypersecretion",                                     "SALIVATION",                                          "GASTROINTESTINAL DISORDERS",  10039428,  10017947,
  "Urinary Tract Infection",                              "URINARY INFECTION",                                         "INFECTIONS AND INFESTATIONS",  10046544,  10021881,
  "Chest Pain",                                     "CHEST PAIN",                "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10008479,  10018065,
  "Haemoptysis",                                 "COUGHING BLOOD",                     "RESPIRATORY, THORACIC AND MEDIASTINAL DISORDERS",  10011234,  10038738,
  "Rales",                                          "RALES",                     "RESPIRATORY, THORACIC AND MEDIASTINAL DISORDERS",  10037833,  10038738,
  "Skin Exfoliation",                                   "SKIN PEELING",                              "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10040908,  10040785,
  "Application Site Induration",                    "APPLICATION SITE INDURATION",                "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10063839,  10018065,
  "Fall",                                   "FALLING DOWN",                      "INJURY, POISONING AND PROCEDURAL COMPLICATIONS",  10016178,  10022117,
  "Insomnia",                            "DIFFICULTY SLEEPING",                                               "PSYCHIATRIC DISORDERS",  10012804,  10037175,
  "Gastrointestinal Haemorrhage",                                       "GI BLEED",                                          "GASTROINTESTINAL DISORDERS",  10018230,  10017947,
  "Supraventricular Extrasystoles",                   "PREMATURE ATRIAL CONTRACTION",                                                   "CARDIAC DISORDERS",  10056964,  10007541,
  "Myocardial Infarction",                             "MYOCARDIAL INFARCT",                                                   "CARDIAC DISORDERS",  10028595,  10007541,
  "Syncope Vasovagal",                              "SYNCOPE VASOVAGAL",                                            "NERVOUS SYSTEM DISORDERS",  10042777,  10029205,
  "Complex Partial Seizures",                       "COMPLEX PARTIAL SEIZURES",                                            "NERVOUS SYSTEM DISORDERS",  10010145,  10029205,
  "Skin Laceration",                             "LACERATION OF HEAD",                      "INJURY, POISONING AND PROCEDURAL COMPLICATIONS",  10023587,  10022117,
  "Atrioventricular Block First Degree",            "FIRST DEGREE ATRIOVENTRICULAR BLOCK",                                                   "CARDIAC DISORDERS",  10016699,  10007541,
  "Cold Sweat",                                     "COLD SWEAT",                              "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10009866,  10040785,
  "Atrial Fibrillation",                 "PAROXYSMAL ATRIAL FIBRILLATION",                                                   "CARDIAC DISORDERS",  10034039,  10007541,
  "Cardiac Failure Congestive",                       "CONGESTIVE HEART FAILURE",                                                   "CARDIAC DISORDERS",  10010684,  10007541,
  "Hyponatraemia",                                   "HYPONATREMIA",                                  "METABOLISM AND NUTRITION DISORDERS",  10021038,  10027433,
  "Blister",                                       "BLISTERS",                              "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10005216,  10040785,
  "Nasopharyngitis",                                    "COMMON COLD",                                         "INFECTIONS AND INFESTATIONS",  10010106,  10021881,
  "Application Site Desquamation",                  "APPLICATION SITE DESQUAMATION",                "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",        NA,        NA,
  "Delusion",                                      "DELUSIONS",                                               "PSYCHIATRIC DISORDERS",  10012260,  10037175,
  "Hip Fracture",                                  "FRACTURED HIP",                      "INJURY, POISONING AND PROCEDURAL COMPLICATIONS",  10017287,  10022117,
  "Psychomotor Hyperactivity",                             "INCREASED ACTIVITY",                                            "NERVOUS SYSTEM DISORDERS",  10021650,  10029205,
  "Electrocardiogram t Wave Amplitude Decreased",                           "T WAVE FLATTENING OF",                                                      "INVESTIGATIONS",  10042965,  10022891,
  "Supraventricular Tachycardia",                   "SUPRAVENTRICULAR TACHYCARDIA",                                                   "CARDIAC DISORDERS",  10042604,  10007541,
  "Ear Infection",                                  "EAR INFECTION",                                         "INFECTIONS AND INFESTATIONS",  10014011,  10021881,
  "Glossitis",                                      "GLOSSITIS",                                          "GASTROINTESTINAL DISORDERS",  10018386,  10017947,
  "Headache",                          "INTERMITTENT HEADACHE",                                            "NERVOUS SYSTEM DISORDERS",  10059296,  10029205,
  "Cerumen Impaction",                              "CERUMEN IMPACTION",                                         "EAR AND LABYRINTH DISORDERS",  10050337,  10013993,
  "Conjunctival Haemorrhage",                     "SUBCONJUNCTIVAL HEMORRHAGE",                                                       "EYE DISORDERS",  10055345,  10015919,
  "Paraesthesia Oral",                                 "TINGLING MOUTH",                                            "NERVOUS SYSTEM DISORDERS",  10049315,  10029205,
  "Rash Pruritic",                                     "ITCHY RASH",                              "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10023092,  10040785,
  "Supraventricular Extrasystoles",                           "ECTOPIC ATRIAL BEATS",                                                   "CARDIAC DISORDERS",  10050077,  10007541,
  "Tinnitus",                                       "TINNITUS",                                         "EAR AND LABYRINTH DISORDERS",  10043882,  10013993,
  "Ventricular Extrasystoles",             "PREMATURE VENTRICULAR CONTRACTIONS",                                                   "CARDIAC DISORDERS",  10036614,  10007541,
  "Asthenia",                                       "WEAKNESS",                "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10047862,  10018065,
  "Hypertension",                                   "HYPERTENSION",                                                  "VASCULAR DISORDERS",  10020772,  10047065,
  "Vomiting",                                         "EMESIS",                                          "GASTROINTESTINAL DISORDERS",  10014542,  10017947,
  "Back Pain",                                      "BACK PAIN",                     "MUSCULOSKELETAL AND CONNECTIVE TISSUE DISORDERS",  10003988,  10028395,
  "Delirium",                                       "DELIRIUM",                                               "PSYCHIATRIC DISORDERS",  10012218,  10037175,
  "Asthenia",                  "LOWER EXTREMITIES WEAKNESS OF",                "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",        NA,        NA,
  "Cervicitis",                                     "CERVICITIS",                                         "INFECTIONS AND INFESTATIONS",  10008323,  10021881,
  "Dyspepsia",                                      "HEARTBURN",                                          "GASTROINTESTINAL DISORDERS",  10019326,  10017947,
  "Dysuria",                            "MICTURITION BURNING",                                         "RENAL AND URINARY DISORDERS",  10027560,  10038359,
  "Gastroenteritis Viral",                                    "STOMACH FLU",                                         "INFECTIONS AND INFESTATIONS",  10042105,  10021881,
  "Gastrooesophageal Reflux Disease",               "GASTROOESOPHAGEAL REFLUX DISEASE",                                          "GASTROINTESTINAL DISORDERS",  10017885,  10017947,
  "Pelvic Pain",                                    "PELVIC PAIN",                            "REPRODUCTIVE SYSTEM AND BREAST DISORDERS",  10034263,  10038604,
  "Vaginal Mycosis",                        "VAGINAL YEAST INFECTION",                                         "INFECTIONS AND INFESTATIONS",        NA,        NA,
  "Bronchitis",                                     "BRONCHITIS",                                         "INFECTIONS AND INFESTATIONS",  10006451,  10021881,
  "Bundle Branch Block Right",           "INCOMPLETE RIGHT BUNDLE BRANCH BLOCK",                                                   "CARDIAC DISORDERS",  10051862,  10007541,
  "Electrocardiogram t Wave Inversion",                               "T WAVE INVERSION",                                                      "INVESTIGATIONS",  10042966,  10022891,
  "Application Site Pruritus",                      "APPLICATION SITE PRURITUS",                "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10003053,  10018065,
  "Diarrhoea",                                   "LOOSE STOOLS",                                          "GASTROINTESTINAL DISORDERS",  10024840,  10017947,
  "Dysuria",                           "URINATION DIFFICULTY",                                         "RENAL AND URINARY DISORDERS",  10046599,  10038359,
  "Back Pain",                                  "LOW BACK PAIN",                     "MUSCULOSKELETAL AND CONNECTIVE TISSUE DISORDERS",  10024891,  10028395,
  "Nasopharyngitis",                                      "HEAD COLD",                                         "INFECTIONS AND INFESTATIONS",  10019192,  10021881,
  "Ear Pain",                                       "EAR PAIN",                                         "EAR AND LABYRINTH DISORDERS",  10014020,  10013993,
  "Dermatitis Contact",                             "CONTACT DERMATITIS",                              "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10010790,  10040785,
  "Nephrolithiasis",                                  "KIDNEY STONES",                                         "RENAL AND URINARY DISORDERS",  10023437,  10038359,
  "Application Site Reaction",                      "APPLICATION SITE REACTION",                "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10003055,  10018065,
  "Emphysema",                                      "EMPHYSEMA",                     "RESPIRATORY, THORACIC AND MEDIASTINAL DISORDERS",  10014561,  10038738,
  "Lethargy",                                       "LETHARGY",                                            "NERVOUS SYSTEM DISORDERS",  10024264,  10029205,
  "Restlessness",                                   "RESTLESSNESS",                                               "PSYCHIATRIC DISORDERS",  10038743,  10037175,
  "Hypersomnia",                                "SLEEP EXCESSIVE",                                            "NERVOUS SYSTEM DISORDERS",  10041000,  10029205,
  "Malignant Fibrous Histiocytoma",                 "MALIGNANT FIBROUS HISTIOCYTOMA", "NEOPLASMS BENIGN, MALIGNANT AND UNSPECIFIED (INCL CYSTS AND POLYPS)",  10025552,  10029104,
  "Hypersensitivity",                                        "ALLERGY",                                             "IMMUNE SYSTEM DISORDERS",  10001738,  10021428,
  "Pruritus",                                           "ITCH",                              "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10023082,  10040785,
  "Swelling",                                       "SWELLING",                "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10042674,  10018065,
  "Hallucination",                                  "HALLUCINATION",                                               "PSYCHIATRIC DISORDERS",  10019063,  10037175,
  "Prostate Cancer",                                "PROSTATE CANCER", "NEOPLASMS BENIGN, MALIGNANT AND UNSPECIFIED (INCL CYSTS AND POLYPS)",  10060862,  10029104,
  "Blood Cholesterol Increased",                               "HIGH CHOLESTEROL",                                                      "INVESTIGATIONS",  10020049,  10022891,
  "Ulcer",                                          "ULCER",                "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10045285,  10018065,
  "Cognitive Disorder",                           "COGNITIVE IMPAIRMENT",                                            "NERVOUS SYSTEM DISORDERS",  10009846,  10029205,
  "Anxiety",                                        "ANXIETY",                                               "PSYCHIATRIC DISORDERS",  10002855,  10037175,
  "Diarrhoea",                                    "SOFT STOOLS",                                          "GASTROINTESTINAL DISORDERS",  10048838,  10017947,
  "Enuresis",                                    "BED WETTING",                                         "RENAL AND URINARY DISORDERS",  10004197,  10038359,
  "Wound",                                      "WOUND NOS",                      "INJURY, POISONING AND PROCEDURAL COMPLICATIONS",  10051583,  10022117,
  "Alopecia",                                      "HAIR LOSS",                              "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10019045,  10040785,
  "Nasal Congestion",                                "NOSE CONGESTION",                     "RESPIRATORY, THORACIC AND MEDIASTINAL DISORDERS",  10029794,  10038738,
  "Oedema Peripheral",                                    "ANKLE EDEMA",                "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10002542,  10018065,
  "Anxiety",                             "ANXIETY AGGRAVATED",                                               "PSYCHIATRIC DISORDERS",  10048339,  10037175,
  "Inflammation",                         "INFLAMMATION LOCALIZED",                "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10021959,  10018065,
  "Somnolence",                                     "SLEEPINESS",                                            "NERVOUS SYSTEM DISORDERS",  10041014,  10029205,
  "Bradycardia",                                    "BRADYCARDIA",                                                   "CARDIAC DISORDERS",  10006093,  10007541,
  "Food Craving",                           "CARBOHYDRATE CRAVING",                                  "METABOLISM AND NUTRITION DISORDERS",  10007216,  10027433,
  "Agitation",                            "INCREASED AGITATION",                                               "PSYCHIATRIC DISORDERS",  10021651,  10037175,
  "Body Temperature Increased",                          "TEMPERATURE ELEVATION",                                                      "INVESTIGATIONS",  10043204,  10022891,
  "Hyperhidrosis",                                    "DIAPHORESIS",                              "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10012703,  10040785,
  "Balance Disorder",                                   "UNSTEADINESS",                                            "NERVOUS SYSTEM DISORDERS",  10046260,  10029205,
  "Coordination Abnormal",                                 "INCOORDINATION",                                            "NERVOUS SYSTEM DISORDERS",  10021649,  10029205,
  "Application Site Discolouration",                 "APPLICATION SITE DISCOLORATION",                "GENERAL DISORDERS AND ADMINISTRATION SITE CONDITIONS",  10059010,  10018065,
  "Arthralgia",                                    "PAIN IN HIP",                     "MUSCULOSKELETAL AND CONNECTIVE TISSUE DISORDERS",  10033432,  10028395,
  "Dysphagia",                           "SWALLOWING DIFFICULT",                                          "GASTROINTESTINAL DISORDERS",  10042645,  10017947,
  "Somnolence",                                     "SOMNOLENCE",                                            "NERVOUS SYSTEM DISORDERS",  10041349,  10029205,
  "Dermatitis Atopic",                              "ATOPIC DERMATITIS",                              "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",  10003639,  10040785,
  "Skin Ulcer",                                   "SKIN EROSION",                              "SKIN AND SUBCUTANEOUS TISSUE DISORDERS",        NA,        NA,
  "Hallucination, Visual",                          "VISUAL HALLUCINATIONS",                                               "PSYCHIATRIC DISORDERS",  10047570,  10037175,
  "Partial Seizures with Secondary Generalisation", "PARTIAL SEIZURES WITH SECONDARY GENERALIZATION",                                            "NERVOUS SYSTEM DISORDERS",  10048674,  10029205,
  "Amnesia",                         "SHORT-TERM MEMORY LOSS",                                            "NERVOUS SYSTEM DISORDERS",  10040602,  10029205
)

meddra <- dplyr::bind_rows(meddra1, meddra2, meddra3)

ae_raw <- ae_raw |>
  dplyr::left_join(meddra, by = c("IT.AETERM", "AELLT", "AESOC")) |>
  dplyr::mutate(AELLTCD = LLT_CODE,
         AESOCCD = SOC_CODE) |>
  dplyr::select(-LLT_CODE, -SOC_CODE)

for (col in names(ae_raw)) {
  attributes(ae_raw[[col]]) <- NULL
}

# Save datasets ----
usethis::use_data(ae_raw, overwrite = TRUE)
